# Generated by Django 5.1.7 on 2025-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='electronics', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='imageLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
